const ADD_PRICE = 'ADD_PRICE';
const REDUCE_PRICE = 'REDUCE_PRICE';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SWAP_INGREDIENTS = 'SWAP_INGREDIENTS';
const ADD_BUN = 'ADD_BUN';
const REMOVE_BUN = 'REMOVE_BUN';

export {
  ADD_PRICE,
  REDUCE_PRICE,
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  SWAP_INGREDIENTS,
  ADD_BUN,
  REMOVE_BUN
};