export const getIngredientsDataState = state => state.ingredientsData;
export const getSelectedIngrState = state => state.selectedIngr;
export const getIngredientDetailsState = state => state.ingredientDetails;
export const getAuthState = state => state.authorization;
export const getOrderIdState = state => state.orderId;
export const getCurrentTabState = state => state.currentTab;
export const forgotPasswordState = state => state.forgotPassword;
export const registerUserState = state => state.registerUser;
export const resetPasswordState = state => state.resetPassword;